### ISSUE TITLE
Existing style tag attributes are not retained during Vue 2 to Vue 3 conversion

### ISSUE THREAD

**Issue by akshay-devadiga** [kalimahapps/tools#2]
Hello,

First of all, thank you for providing such a helpful tool!

While using the tool I noticed a minor issue where the lang attribute for the <style> tag is not being preserved during the Vue 2 to Vue 3 conversion process. This can result in incorrect handling of preprocessors like SCSS or Sass etc.

To address this, I have already created a branch and fixed the issue locally. The changes include:
- Ensuring the composeSfc and parseSfc functions extract and re-apply the lang attribute.
- Updating the formatCode and componentInput function in the helpers file to support styleAttributes as a new  parameter

If you would like, I can create a pull request with the changes for review. 

Thank you once again for this fantastic tool

Preview before the fix - issue
![Issue](https://github.com/user-attachments/assets/14e110f8-a068-4ca7-b9cd-51b65c8858a7)
Preview after the fix
![after fix](https://github.com/user-attachments/assets/325d2eea-563e-4163-b41c-457fabbcc512)

**Comment by abdul-alhasany** [comment]
Sure. Please submit a pull request. 

I did not pay attention to the `style` tag since I was concentrating on the `script` tag.

If you can add tests as well that would be great. If not, I can add it later.

**Comment by akshay-devadiga** [comment]
Update:
Thanks!

I've created a pull request with the fix. Please take a look when you have a moment. 
[Bug Fix: Ensure style tag attributes are preserved during Vue 2 to Vue 3 conversion](https://github.com/kalimahapps/tools/pull/3)

Reg - Tests 
I haven't had a chance to look into it yet, but I'll check it soon and get back to you

**Comment by abdul-alhasany** [comment]
No problem. I merged the request. I can write the tests later when I have time.

Thanks for contributing.
